acl bloqueig dstdomain .facebook.com
http_access deny bloqueig
acl xarxa_interna src 10.0.0.0/8
http_access allow xarxa_interna
http_access deny all
http_port 3128
dns_nameservers 8.8.8.8 8.8.4.4
access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log
visible_hostname squid_proxy_swarm
